# Default values for edc-ionos-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: example.cr.de-fra.ionos.com/ionos-connector
  pullPolicy: Always
  tag: "latest"

imagePullSecret:
  name: "regcred"
  server: ""
  username: ""
  password: ""

nameOverride: ""

fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: LoadBalancer
  apiPort: 8181
  managementPort: 8182
  protocolPort: 8282
  controlPort: 8283
  publicPort: 8383

web:
  http:
    port: 8181
    path: /api
    management:
      port: 8182
      path: /management
    protocol:
      port: 8282
      path: /protocol
    control:
      port: 8283
      path: /control
    public:
      port: 8383
      path: /public
edc:
  keystore: # keystore value base64 encoded
  keystorePassword: # keystore password as string
  oauth:
    tokenUrl: https://omejdn-nginx.example.com/token
    clientId: # from the daps clients.yml
    audience: idsc:IDS_CONNECTORS_ALL
    tokenScope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
    providerJwksUrl: https://omejdn-nginx.example.com/jwks.json
    certificateAlias: 1
    privateKeyAlias: 1
  api:
    auth:
      key: password
  dsp:
    callback:
      address: http://localhost:8282/protocol
  vault:
    clientid: company1
    tenantid: 1
    certificate: /resources/
    name: ionos
    hashicorp:
      url: http://vault:8200
      token:
      timeout:
        seconds: 30
  ionos:
    accessKey: <YOUR-KEY>
    secretKey: <YOUR-SECRET-KEY>
    endpoint: <IONOS-ENDPOINT>
    token: <IONOS-TOKEN>
